# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo $(Agent.BuildDirectory)
    cd $(Agent.BuildDirectory)
    ls
    cd $(Agent.BuildDirectory)/s
    echo $(Agent.BuildDirectory)/s
    ls
  displayName: 'Run a multi-line script'

- task: FlutterInstall@0
  inputs:
    mode: 'auto'
    channel: 'beta'
    version: 'latest'
- task: FlutterBuild@0
  inputs:
    target: 'apk'
    projectDirectory: '$(Agent.BuildDirectory)/s'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Agent.BuildDirectory)/s/build/app/outputs/flutter-apk/app-release.apk'
    ArtifactName: 'drop'
    publishLocation: 'Container'